name: firestore_example
description: Demonstrates how to use the cloud_firestore_mocks plugin.

environment:
  sdk: ">=2.9.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.0
  firebase_core: ^1.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  cloud_firestore_mocks:
    path: ../

flutter:
  uses-material-design: true
