name: firestore_example
description: Demonstrates how to use the cloud_firestore_mocks plugin.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  cloud_firestore_mocks:
    path: ../

flutter:
  uses-material-design: true
