name: cloud_firestore_mocks
description: Mocks for Cloud Firestore. Use this package to write unit tests involving Cloud Firestore.
version: 0.2.7
homepage: http://blog.wafrat.com
author: atn832@gmail.com
repository: https://github.com/atn832/cloud_firestore_mocks

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  mockito: ^4.1.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
